package enity;
// Generated 2018-4-6 19:12:50 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private int CCid;
	private Integer GId;
	private Integer CId;
	private String CText;
	private Date CTime;

	public Comments() {
	}

	public Comments(int CCid, Date CTime) {
		this.CCid = CCid;
		this.CTime = CTime;
	}

	public Comments(int CCid, Integer GId, Integer CId, String CText, Date CTime) {
		this.CCid = CCid;
		this.GId = GId;
		this.CId = CId;
		this.CText = CText;
		this.CTime = CTime;
	}

	public int getCCid() {
		return this.CCid;
	}

	public void setCCid(int CCid) {
		this.CCid = CCid;
	}

	public Integer getGId() {
		return this.GId;
	}

	public void setGId(Integer GId) {
		this.GId = GId;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public String getCText() {
		return this.CText;
	}

	public void setCText(String CText) {
		this.CText = CText;
	}

	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

}
