package enity;
// Generated 2018-4-8 10:13:47 by Hibernate Tools 5.2.3.Final

/**
 * Customter generated by hbm2java
 */
public class Customter implements java.io.Serializable {

	private String CId;
	private String CName;
	private String CPassword;
	private String CIphone;
	private String CAddress;
	private String CImg;

	public Customter() {
	}

	public Customter(String CId) {
		this.CId = CId;
	}

	public Customter(String CId, String CName, String CPassword, String CIphone, String CAddress, String CImg) {
		this.CId = CId;
		this.CName = CName;
		this.CPassword = CPassword;
		this.CIphone = CIphone;
		this.CAddress = CAddress;
		this.CImg = CImg;
	}

	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getCPassword() {
		return this.CPassword;
	}

	public void setCPassword(String CPassword) {
		this.CPassword = CPassword;
	}

	public String getCIphone() {
		return this.CIphone;
	}

	public void setCIphone(String CIphone) {
		this.CIphone = CIphone;
	}

	public String getCAddress() {
		return this.CAddress;
	}

	public void setCAddress(String CAddress) {
		this.CAddress = CAddress;
	}

	public String getCImg() {
		return this.CImg;
	}

	public void setCImg(String CImg) {
		this.CImg = CImg;
	}

}
