package enity;
// Generated 2018-4-6 19:15:15 by Hibernate Tools 5.2.3.Final

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private int GId;
	private String GName;
	private Integer GNum;
	private String GPrice;
	private String GImg;

	public Goods() {
	}

	public Goods(int GId) {
		this.GId = GId;
	}

	public Goods(int GId, String GName, Integer GNum, String GPrice, String GImg) {
		this.GId = GId;
		this.GName = GName;
		this.GNum = GNum;
		this.GPrice = GPrice;
		this.GImg = GImg;
	}

	public int getGId() {
		return this.GId;
	}

	public void setGId(int GId) {
		this.GId = GId;
	}

	public String getGName() {
		return this.GName;
	}

	public void setGName(String GName) {
		this.GName = GName;
	}

	public Integer getGNum() {
		return this.GNum;
	}

	public void setGNum(Integer GNum) {
		this.GNum = GNum;
	}

	public String getGPrice() {
		return this.GPrice;
	}

	public void setGPrice(String GPrice) {
		this.GPrice = GPrice;
	}

	public String getGImg() {
		return this.GImg;
	}

	public void setGImg(String GImg) {
		this.GImg = GImg;
	}

}
