package enity;
// Generated 2018-4-6 19:15:38 by Hibernate Tools 5.2.3.Final

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private int orderId;
	private Integer OId;
	private Integer GId;
	private Integer orderNum;

	public Orderitem() {
	}

	public Orderitem(int orderId) {
		this.orderId = orderId;
	}

	public Orderitem(int orderId, Integer OId, Integer GId, Integer orderNum) {
		this.orderId = orderId;
		this.OId = OId;
		this.GId = GId;
		this.orderNum = orderNum;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Integer getOId() {
		return this.OId;
	}

	public void setOId(Integer OId) {
		this.OId = OId;
	}

	public Integer getGId() {
		return this.GId;
	}

	public void setGId(Integer GId) {
		this.GId = GId;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

}
