package enity;
// Generated 2018-4-6 19:16:10 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int OId;
	private Integer CId;
	private String OPrice;
	private Date OTime;
	private String OState;

	public Orders() {
	}

	public Orders(int OId, Date OTime) {
		this.OId = OId;
		this.OTime = OTime;
	}

	public Orders(int OId, Integer CId, String OPrice, Date OTime, String OState) {
		this.OId = OId;
		this.CId = CId;
		this.OPrice = OPrice;
		this.OTime = OTime;
		this.OState = OState;
	}

	public int getOId() {
		return this.OId;
	}

	public void setOId(int OId) {
		this.OId = OId;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public String getOPrice() {
		return this.OPrice;
	}

	public void setOPrice(String OPrice) {
		this.OPrice = OPrice;
	}

	public Date getOTime() {
		return this.OTime;
	}

	public void setOTime(Date OTime) {
		this.OTime = OTime;
	}

	public String getOState() {
		return this.OState;
	}

	public void setOState(String OState) {
		this.OState = OState;
	}

}
