package enity;
// Generated 2017-12-18 15:33:04 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private String patientBumber;
	private Date inhosDate;
	private String cardId;
	private String customerName;
	private String sex;
	private String sectionoffice;
	private String bedNumber;
	private String faultName;
	private String customerMobilephone;
	private String unitWork;
	private String commonalityName;
	private String medicalModal;
	private String medicalCause;
	private String medicalState;
	private String patientIdentification;
	private String occupation;

	public Test() {
	}

	public Test(String patientBumber, Date inhosDate, String cardId, String customerName, String sex,
			String sectionoffice, String bedNumber, String faultName, String medicalModal, String medicalCause) {
		this.patientBumber = patientBumber;
		this.inhosDate = inhosDate;
		this.cardId = cardId;
		this.customerName = customerName;
		this.sex = sex;
		this.sectionoffice = sectionoffice;
		this.bedNumber = bedNumber;
		this.faultName = faultName;
		this.medicalModal = medicalModal;
		this.medicalCause = medicalCause;
	}

	public Test(String patientBumber, Date inhosDate, String cardId, String customerName, String sex,
			String sectionoffice, String bedNumber, String faultName, String customerMobilephone, String unitWork,
			String commonalityName, String medicalModal, String medicalCause, String medicalState,
			String patientIdentification, String occupation) {
		this.patientBumber = patientBumber;
		this.inhosDate = inhosDate;
		this.cardId = cardId;
		this.customerName = customerName;
		this.sex = sex;
		this.sectionoffice = sectionoffice;
		this.bedNumber = bedNumber;
		this.faultName = faultName;
		this.customerMobilephone = customerMobilephone;
		this.unitWork = unitWork;
		this.commonalityName = commonalityName;
		this.medicalModal = medicalModal;
		this.medicalCause = medicalCause;
		this.medicalState = medicalState;
		this.patientIdentification = patientIdentification;
		this.occupation = occupation;
	}

	public String getPatientBumber() {
		return this.patientBumber;
	}

	public void setPatientBumber(String patientBumber) {
		this.patientBumber = patientBumber;
	}

	public Date getInhosDate() {
		return this.inhosDate;
	}

	public void setInhosDate(Date inhosDate) {
		this.inhosDate = inhosDate;
	}

	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSectionoffice() {
		return this.sectionoffice;
	}

	public void setSectionoffice(String sectionoffice) {
		this.sectionoffice = sectionoffice;
	}

	public String getBedNumber() {
		return this.bedNumber;
	}

	public void setBedNumber(String bedNumber) {
		this.bedNumber = bedNumber;
	}

	public String getFaultName() {
		return this.faultName;
	}

	public void setFaultName(String faultName) {
		this.faultName = faultName;
	}

	public String getCustomerMobilephone() {
		return this.customerMobilephone;
	}

	public void setCustomerMobilephone(String customerMobilephone) {
		this.customerMobilephone = customerMobilephone;
	}

	public String getUnitWork() {
		return this.unitWork;
	}

	public void setUnitWork(String unitWork) {
		this.unitWork = unitWork;
	}

	public String getCommonalityName() {
		return this.commonalityName;
	}

	public void setCommonalityName(String commonalityName) {
		this.commonalityName = commonalityName;
	}

	public String getMedicalModal() {
		return this.medicalModal;
	}

	public void setMedicalModal(String medicalModal) {
		this.medicalModal = medicalModal;
	}

	public String getMedicalCause() {
		return this.medicalCause;
	}

	public void setMedicalCause(String medicalCause) {
		this.medicalCause = medicalCause;
	}

	public String getMedicalState() {
		return this.medicalState;
	}

	public void setMedicalState(String medicalState) {
		this.medicalState = medicalState;
	}

	public String getPatientIdentification() {
		return this.patientIdentification;
	}

	public void setPatientIdentification(String patientIdentification) {
		this.patientIdentification = patientIdentification;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

}
