package enity;
// Generated 2018-3-31 21:26:46 by Hibernate Tools 5.2.3.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private String userName;
	private Boolean activeState;
	private String loginName;
	private String description;
	private String password;

	public User() {
	}

	public User(String userName, Boolean activeState, String loginName, String description, String password) {
		this.userName = userName;
		this.activeState = activeState;
		this.loginName = loginName;
		this.description = description;
		this.password = password;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Boolean getActiveState() {
		return this.activeState;
	}

	public void setActiveState(Boolean activeState) {
		this.activeState = activeState;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
